name: CI
on:
  push:
    branches-ignore:
      - 'renovate/3rd-party**' # Do not build 3rd party package updates automatically to avoid some hacked package stealing all our secrets https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir release
          npm install
          npm run all
          cp -R dist action.yml release/

      - name: Test
        uses: ./release
        with:
          baseVersion: 1.2.3

      - name: Release branch name
        id: release_branch_name
        run: |
          branch=latest

          if [[ $GITHUB_REF != refs/heads/main ]]; then
            branch=dev-${GITHUB_REF#refs/heads/}
          fi

          echo "branch=$branch"
          echo "branch=$branch" >> $GITHUB_OUTPUT
          
      - name: Publish into release branch
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: ${{ steps.release_branch_name.outputs.branch }}
          FOLDER: release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
